services:
  caddy:
    build:
      context: ./dockerfiles/caddy
      args:
        - APP_ENV=$APP_ENV
        - APP_URL=$APP_URL
    restart: unless-stopped
    volumes:
      - ./src/:/var/www/
      - ./dockerfiles/caddy/data/config:/config
      - ./dockerfiles/caddy/data/data:/data
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
    env_file: .env
  php:
    build:
      context: ./dockerfiles/php
      args:
        - APP_ENV=$APP_ENV
        - PHP_XDEBUG=$PHP_XDEBUG
        - PHP_XDEBUG_MODE=$PHP_XDEBUG_MODE
    restart: unless-stopped
    volumes:
       - ./src/:/var/www/
    expose:
      - 9000
    depends_on:
      - database
    env_file: .env
    extra_hosts:
      host.docker.internal: host-gateway
  workspace:
    build:
      context: ./dockerfiles/workspace
      args:
        - PHP_XDEBUG=$PHP_XDEBUG
        - PHP_XDEBUG_MODE=$PHP_XDEBUG_MODE
    tty: true
    ports:
      - 1234:1234
    volumes:
      - ./src/:/var/www/
    extra_hosts:
      host.docker.internal: host-gateway
  database:
    image: mysql:8.0.29
    restart: unless-stopped
    volumes:
      - ./dockerfiles/mysql/data:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}